displayName=Detect Auto Alchers
author=zjohnson
description=Highlights nearby suspected auto-alchers for manual investigation
tags=alchemy,alch,bot,report,highlight,hiscore
plugins=com.detectautoalchers.DetectAutoAlchersPlugin
